- name: パッケージリストを更新
  apt:
    update_cache: yes

- name: 必要なパッケージをインストール
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add ll alias to .bashrc
  lineinfile:
    path: /home/admin/.bashrc
    line: "alias ll='ls -al'"
