- name: Remove existing Docker GPG key if it exists
  ansible.builtin.file:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
    state: absent

- name: Download Docker GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  ansible.builtin.shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: パッケージリストを更新
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add user to Docker group
  ansible.builtin.user:
    name: admin
    groups: docker
    append: yes

- name: Copy compose.yml
  ansible.builtin.copy:
    src: compose.yml
    dest: /home/admin
    mode: '0644'